### ISSUE TITLE
consolidate pib-webv

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/pib-cli#501]
- currently have 3 docker images
- webv-red
- voe-webv
- webv-vote

consolidate to cse-labs/pib-webv

**Comment by kev-ms** [comment]
Updated all docker references to pib-* for these repos:
- pib-gitops
- pib-dev
- pib-cli
- bartr-fleet
- voe-fleet

Bigger refactor is required for these repos, created triage on board:
- red-gitops
- pib-vote
- pib-tlog
