### ISSUE TITLE
create voe-fleet

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/pib-cli#595]
- have to recreate in the new subscription

**Comment by aflinchb** [comment]
I'll leave this open to track recreating the voe-fleet to test all the new updates to pib-gitops when ready.

**Comment by aflinchb** [comment]
Closing as the fleet was created in the new subscription. 
https://github.com/retaildevcrews/pib-cli/issues/623 will track recreating with ssl once pib-gitops changes are ready to be tested.
