### ISSUE TITLE
Publish voe module images to cse-labs

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/pib-cli#619]

**Comment by aflinchb** [comment]
Proposed naming:
- pib-voe-cvcapture
- pib-voe-inference
- pib-voe-predict
- pib-voe-rtspsim
- pib-voe-upload
- pib-voe-web

**Comment by bartr** [comment]
- should we change cvcapture to capture?
- is there a friendlier name for rtspsim?

I'm OK as proposed or with one or both changes.

**Comment by aflinchb** [comment]
I'm going to leave as is to keep it consistent with the deployment/service naming in the existing yaml and the module names: 
![image](https://user-images.githubusercontent.com/3301452/181360340-86d1e505-5b39-43bb-9583-d4907cfd4a95.png)

**Comment by aflinchb** [comment]
I published the images manually: https://github.com/orgs/cse-labs/packages?tab=packages&q=voe

Will update the ci/cd pipeline in the voe-app repo and close this task after India crew is done using the repo to record a checkpoint demo.
